name: Run Tests

on: workflow_call

jobs:
  dotnet-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-dotnet@v3
        with:
          global-json-file: ./global.json

      - run: dotnet test
